### ISSUE TITLE
PermissionError

### ISSUE THREAD

**Issue by velikaplan** [cocktailpeanut/mirror#13]
Hello everyone,
I get the following error.

PermissionError: [WinError 32] The file is distributed by another process but this process cannot access the file: 'D:\\mirror\\cache\\TEMP\\tmpls714zfm'
ERROR:    Exception in ASGI application
Traceback (most recent call last):
  File "D:\mirror\bin\miniconda\lib\shutil.py", line 816, in move
    os.rename(src, real_dst)
PermissionError: [WinError 32] The file is distributed by another process but this process cannot access the file: 'D:\\mirror\\cache\\TEMP\\tmp09puxx2y' -> 'D:\\mirror\\cache\\TEMP\\gradio\\f00584179e8e318c202d73d9ce75bc457ac415ac\\webcam.png'

During handling of the above exception, another exception occurred

**Comment by chillbert** [comment]
same here.

Webserver starts, webcam starts, but as soon as you change the prompt this errors occurs in the backend console...

```
`During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\person1\pinokio\api\mirror.git\venv\lib\site-packages\uvicorn\protocols\http\h11_impl.py", line 408, in run_asgi
    result = await app(  # type: ignore[func-returns-value]
  File "C:\Users\person1\pinokio\api\mirror.git\venv\lib\site-packages\uvicorn\middleware\proxy_headers.py", line 84, in __call__
    return await self.app(scope, receive, send)
  File "C:\Users\person1\pinokio\api\mirror.git\venv\lib\site-packages\fastapi\applications.py", line 1106, in __call__
    await super().__call__(scope, receive, send)
  File "C:\Users\person1\pinokio\api\mirror.git\venv\lib\site-packages\starlette\applications.py", line 122, in __call__
    await self.middleware_stack(scope, receive, send)
  File "C:\Users\person1\pinokio\api\mirror.git\venv\lib\site-packages\starlette\middleware\errors.py", line 184, in __call__
    raise exc
  File "C:\Users\person1\pinokio\api\mirror.git\venv\lib\site-packages\starlette\middleware\errors.py", line 162, in __call__
    await self.app(scope, receive, _send)
  File "C:\Users\person1\pinokio\api\mirror.git\venv\lib\site-packages\starlette\middleware\cors.py", line 91, in __call__
    await self.simple_response(scope, receive, send, request_headers=headers)
  File "C:\Users\person1\pinokio\api\mirror.git\venv\lib\site-packages\starlette\middleware\cors.py", line 146, in simple_response
    await self.app(scope, receive, send)
  File "C:\Users\person1\pinokio\api\mirror.git\venv\lib\site-packages\starlette\middleware\exceptions.py", line 79, in __call__
    raise exc
  File "C:\Users\person1\pinokio\api\mirror.git\venv\lib\site-packages\starlette\middleware\exceptions.py", line 68, in __call__
    await self.app(scope, receive, sender)
  File "C:\Users\person1\pinokio\api\mirror.git\venv\lib\site-packages\fastapi\middleware\asyncexitstack.py", line 20, in __call__
    raise e
  File "C:\Users\person1\pinokio\api\mirror.git\venv\lib\site-packages\fastapi\middleware\asyncexitstack.py", line 17, in __call__
    await self.app(scope, receive, send)
  File "C:\Users\person1\pinokio\api\mirror.git\venv\lib\site-packages\starlette\routing.py", line 718, in __call__
    await route.handle(scope, receive, send)
  File "C:\Users\person1\pinokio\api\mirror.git\venv\lib\site-packages\starlette\routing.py", line 276, in handle
    await self.app(scope, receive, send)
  File "C:\Users\person1\pinokio\api\mirror.git\venv\lib\site-packages\starlette\routing.py", line 66, in app
    response = await func(request)
  File "C:\Users\person1\pinokio\api\mirror.git\venv\lib\site-packages\fastapi\routing.py", line 274, in app
    raw_response = await run_endpoint_function(
  File "C:\Users\person1\pinokio\api\mirror.git\venv\lib\site-packages\fastapi\routing.py", line 191, in run_endpoint_function
    return await dependant.call(**values)
  File "C:\Users\person1\pinokio\api\mirror.git\venv\lib\site-packages\gradio\routes.py", line 710, in upload_file
    await anyio.to_thread.run_sync(
  File "C:\Users\person1\pinokio\api\mirror.git\venv\lib\site-packages\anyio\to_thread.py", line 33, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "C:\Users\person1\pinokio\api\mirror.git\venv\lib\site-packages\anyio\_backends\_asyncio.py", line 877, in run_sync_in_worker_thread
    return await future
  File "C:\Users\person1\pinokio\api\mirror.git\venv\lib\site-packages\anyio\_backends\_asyncio.py", line 807, in run
    result = context.run(func, *args)
  File "C:\Users\person1\pinokio\bin\miniconda\lib\shutil.py", line 837, in move
    os.unlink(src)
PermissionError: [WinError 32] The process cannot access the file because it is being used by another process: 'C:\\Users\\person1\\pinokio\\cache\\TMP\\tmphniqvnrd'
ERROR:    Exception in ASGI application
Traceback (most recent call last):
  File "C:\Users\person1\pinokio\bin\miniconda\lib\shutil.py", line 816, in move
    os.rename(src, real_dst)
PermissionError: [WinError 32] The process cannot access the file because it is being used by another process: 'C:\\Users\\person1\\pinokio\\cache\\TMP\\tmp5foo600y' -> 'C:\\Users\\person1\\pinokio\\cache\\TMP\\gradio\\9da7a7d8ecf99ca13c352248c411dfe593ba7c7d\\webcam.png'

During handling of the above exception, another exception occurred:
`
```

**Comment by alielsayid** [comment]
Same here, 

The web server starts, webcam starts, but I get this error:

PermissionError: [WinError 32] The process cannot access the file because it is being used by another process: 'C:\\Users\\aliel\\pinokio\\cache\\TMPDIR\\tmpvllrusi0'
ERROR:    Exception in ASGI application

**Comment by Mubeen202** [comment]
i don't know from where we can run this as an administrative

**Comment by tomvanderputte** [comment]
Same here, run as admin did not change this

**Comment by sebastiantrella** [comment]
same problem here running in Pinokio as administrator...

**Comment by sebastiantrella** [comment]
same problem here running in Pinokio as administrator...

PermissionError: [WinError 32] Der Prozess kann nicht auf die Datei zugreifen, da sie von einem anderen Prozess verwendet wird: 'C:\\Pinokio\\cache\\TMPDIR\\tmpnky888ef'
ERROR:    Exception in ASGI application
Traceback (most recent call last):
  File "C:\Pinokio\bin\miniconda\lib\shutil.py", line 816, in move
    os.rename(src, real_dst)
PermissionError: [WinError 32] Der Prozess kann nicht auf die Datei zugreifen, da sie von einem anderen Prozess verwendet wird: 'C:\\Pinokio\\cache\\TMPDIR\\tmpjdfucl_x' -> 'C:\\Pinokio\\cache\\GRADIO_TEMP_DIR\\0540fb0365f135ad61a21c2dc434720eb541e16f\\webcam.png'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Pinokio\api\mirror.git\venv\lib\site-packages\uvicorn\protocols\http\httptools_impl.py", line 399, in run_asgi
    result = await app(  # type: ignore[func-returns-value]
  File "C:\Pinokio\api\mirror.git\venv\lib\site-packages\uvicorn\middleware\proxy_headers.py", line 70, in __call__
    return await self.app(scope, receive, send)
  File "C:\Pinokio\api\mirror.git\venv\lib\site-packages\fastapi\applications.py", line 1054, in __call__
    await super().__call__(scope, receive, send)
  File "C:\Pinokio\api\mirror.git\venv\lib\site-packages\starlette\applications.py", line 123, in __call__
    await self.middleware_stack(scope, receive, send)
  File "C:\Pinokio\api\mirror.git\venv\lib\site-packages\starlette\middleware\errors.py", line 186, in __call__
    raise exc
  File "C:\Pinokio\api\mirror.git\venv\lib\site-packages\starlette\middleware\errors.py", line 164, in __call__
    await self.app(scope, receive, _send)
  File "C:\Pinokio\api\mirror.git\venv\lib\site-packages\starlette\middleware\cors.py", line 93, in __call__
    await self.simple_response(scope, receive, send, request_headers=headers)
  File "C:\Pinokio\api\mirror.git\venv\lib\site-packages\starlette\middleware\cors.py", line 148, in simple_response
    await self.app(scope, receive, send)
  File "C:\Pinokio\api\mirror.git\venv\lib\site-packages\starlette\middleware\exceptions.py", line 65, in __call__
    await wrap_app_handling_exceptions(self.app, conn)(scope, receive, send)
  File "C:\Pinokio\api\mirror.git\venv\lib\site-packages\starlette\_exception_handler.py", line 64, in wrapped_app
    raise exc
  File "C:\Pinokio\api\mirror.git\venv\lib\site-packages\starlette\_exception_handler.py", line 53, in wrapped_app
    await app(scope, receive, sender)
  File "C:\Pinokio\api\mirror.git\venv\lib\site-packages\starlette\routing.py", line 756, in __call__
    await self.middleware_stack(scope, receive, send)
  File "C:\Pinokio\api\mirror.git\venv\lib\site-packages\starlette\routing.py", line 776, in app
    await route.handle(scope, receive, send)
  File "C:\Pinokio\api\mirror.git\venv\lib\site-packages\starlette\routing.py", line 297, in handle
    await self.app(scope, receive, send)
  File "C:\Pinokio\api\mirror.git\venv\lib\site-packages\starlette\routing.py", line 77, in app
    await wrap_app_handling_exceptions(app, request)(scope, receive, send)
  File "C:\Pinokio\api\mirror.git\venv\lib\site-packages\starlette\_exception_handler.py", line 64, in wrapped_app
    raise exc
  File "C:\Pinokio\api\mirror.git\venv\lib\site-packages\starlette\_exception_handler.py", line 53, in wrapped_app
    await app(scope, receive, sender)
  File "C:\Pinokio\api\mirror.git\venv\lib\site-packages\starlette\routing.py", line 72, in app
    response = await func(request)
  File "C:\Pinokio\api\mirror.git\venv\lib\site-packages\fastapi\routing.py", line 278, in app
    raw_response = await run_endpoint_function(
  File "C:\Pinokio\api\mirror.git\venv\lib\site-packages\fastapi\routing.py", line 191, in run_endpoint_function
    return await dependant.call(**values)
  File "C:\Pinokio\api\mirror.git\venv\lib\site-packages\gradio\routes.py", line 710, in upload_file
    await anyio.to_thread.run_sync(
  File "C:\Pinokio\api\mirror.git\venv\lib\site-packages\anyio\to_thread.py", line 56, in run_sync
    return await get_async_backend().run_sync_in_worker_thread(
  File "C:\Pinokio\api\mirror.git\venv\lib\site-packages\anyio\_backends\_asyncio.py", line 2177, in run_sync_in_worker_thread
    return await future
  File "C:\Pinokio\api\mirror.git\venv\lib\site-packages\anyio\_backends\_asyncio.py", line 859, in run
    result = context.run(func, *args)
  File "C:\Pinokio\bin\miniconda\lib\shutil.py", line 837, in move
    os.unlink(src)
PermissionError: [WinError 32] Der Prozess kann nicht auf die Datei zugreifen, da sie von einem anderen Prozess verwendet wird: 'C:\\Pinokio\\cache\\TMPDIR\\tmpjdfucl_x'
ERROR:    Exception in ASGI application
Traceback (most recent call last):
  File "C:\Pinokio\bin\miniconda\lib\shutil.py", line 816, in move
    os.rename(src, real_dst)
PermissionError: [WinError 32] Der Prozess kann nicht auf die Datei zugreifen, da sie von einem anderen Prozess verwendet wird: 'C:\\Pinokio\\cache\\TMPDIR\\tmptzbkt7im' -> 'C:\\Pinokio\\cache\\GRADIO_TEMP_DIR\\59b6509bba0262d4285ff6bb015f653239f350ac\\webcam.png'

**Comment by octadion** [comment]
@velikaplan try gradio 4.1.1

**Comment by Anubiiiiiiiiiis** [comment]
I have the same problem! Nobody can resolve this? Why i have this problem?

@octadion how i can change version of gradio in Pinokio?

Thank you

**Comment by sebastiantrella** [comment]
> @velikaplan try gradio 4.1.1

How can I do this?

**Comment by Anubiiiiiiiiiis** [comment]
@velikaplan I have update gradio to version 4.1.1 , seems works but.. show this error now:

Traceback (most recent call last):
  File "C:\pinokio\api\mirror.git\venv\lib\site-packages\urllib3\connection.py", line 196, in _new_conn
    sock = connection.create_connection(
  File "C:\pinokio\api\mirror.git\venv\lib\site-packages\urllib3\util\connection.py", line 85, in create_connection
    raise err
  File "C:\pinokio\api\mirror.git\venv\lib\site-packages\urllib3\util\connection.py", line 73, in create_connection
    sock.connect(sa)
ConnectionRefusedError: [WinError 10061] Unable to establish connection. Persistent rejection of the target computer
The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\pinokio\api\mirror.git\venv\lib\site-packages\urllib3\connectionpool.py", line 789, in urlopen
    response = self._make_request(
  File "C:\pinokio\api\mirror.git\venv\lib\site-packages\urllib3\connectionpool.py", line 495, in _make_request
    conn.request(
  File "C:\pinokio\api\mirror.git\venv\lib\site-packages\urllib3\connection.py", line 398, in request
    self.endheaders()
  File "C:\pinokio\bin\miniconda\lib\http\client.py", line 1278, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "C:\pinokio\bin\miniconda\lib\http\client.py", line 1038, in _send_output
    self.send(msg)
  File "C:\pinokio\bin\miniconda\lib\http\client.py", line 976, in send
    self.connect()
  File "C:\pinokio\api\mirror.git\venv\lib\site-packages\urllib3\connection.py", line 236, in connect
    self.sock = self._new_conn()
  File "C:\pinokio\api\mirror.git\venv\lib\site-packages\urllib3\connection.py", line 211, in _new_conn
    raise NewConnectionError(
urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPConnection object at 0x00000266BDD1CEB0>: Failed to establish a new connection: [WinError 10061] Unable to establish connection. Persistent rejection of the target computer

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\pinokio\api\mirror.git\venv\lib\site-packages\requests\adapters.py", line 667, in send
    resp = conn.urlopen(
  File "C:\pinokio\api\mirror.git\venv\lib\site-packages\urllib3\connectionpool.py", line 843, in urlopen
    retries = retries.increment(
  File "C:\pinokio\api\mirror.git\venv\lib\site-packages\urllib3\util\retry.py", line 519, in increment
    raise MaxRetryError(_pool, url, reason) from reason  # type: ignore[arg-type]
urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='localhost', port=8080): Max retries exceeded with url: /completion (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x00000266BDD1CEB0>: Failed to establish a new connection: [WinError 10061] Unable to establish connection. Persistent rejection of the target computer'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\pinokio\api\mirror.git\venv\lib\site-packages\gradio\queueing.py", line 427, in call_prediction
    output = await route_utils.call_process_api(
  File "C:\pinokio\api\mirror.git\venv\lib\site-packages\gradio\route_utils.py", line 232, in call_process_api
    output = await app.get_blocks().process_api(
  File "C:\pinokio\api\mirror.git\venv\lib\site-packages\gradio\blocks.py", line 1484, in process_api
    result = await self.call_function(
  File "C:\pinokio\api\mirror.git\venv\lib\site-packages\gradio\blocks.py", line 1118, in call_function
    prediction = await utils.async_iteration(iterator)
  File "C:\pinokio\api\mirror.git\venv\lib\site-packages\gradio\utils.py", line 514, in async_iteration
    return await iterator.__anext__()
  File "C:\pinokio\api\mirror.git\venv\lib\site-packages\gradio\utils.py", line 507, in __anext__
    return await anyio.to_thread.run_sync(
  File "C:\pinokio\api\mirror.git\venv\lib\site-packages\anyio\to_thread.py", line 56, in run_sync
    return await get_async_backend().run_sync_in_worker_thread(
  File "C:\pinokio\api\mirror.git\venv\lib\site-packages\anyio\_backends\_asyncio.py", line 2177, in run_sync_in_worker_thread
    return await future
  File "C:\pinokio\api\mirror.git\venv\lib\site-packages\anyio\_backends\_asyncio.py", line 859, in run
    result = context.run(func, *args)
  File "C:\pinokio\api\mirror.git\venv\lib\site-packages\gradio\utils.py", line 490, in run_sync_iterator_async
    return next(iterator)
  File "C:\pinokio\api\mirror.git\venv\lib\site-packages\gradio\utils.py", line 653, in gen_wrapper
    yield from f(*args, **kwargs)
  File "C:\pinokio\api\mirror.git\app.py", line 25, in run
    response = requests.post(url, headers=headers, json=data, stream=True)
  File "C:\pinokio\api\mirror.git\venv\lib\site-packages\requests\api.py", line 115, in post
    return request("post", url, data=data, json=json, **kwargs)
  File "C:\pinokio\api\mirror.git\venv\lib\site-packages\requests\api.py", line 59, in request
    return session.request(method=method, url=url, **kwargs)
  File "C:\pinokio\api\mirror.git\venv\lib\site-packages\requests\sessions.py", line 589, in request
    resp = self.send(prep, **send_kwargs)
  File "C:\pinokio\api\mirror.git\venv\lib\site-packages\requests\sessions.py", line 703, in send
    r = adapter.send(request, **kwargs)
  File "C:\pinokio\api\mirror.git\venv\lib\site-packages\requests\adapters.py", line 700, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPConnectionPool(host='localhost', port=8080): Max retries exceeded with url: /completion (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x00000266BDD1CEB0>: Failed to establish a new connection: [WinError 10061] Unable to establish connection. Persistent rejection of the target computer'))
Traceback (most recent call last):
  File "C:\pinokio\api\mirror.git\venv\lib\site-packages\urllib3\connection.py", line 196, in _new_conn
    sock = connection.create_connection(
  File "C:\pinokio\api\mirror.git\venv\lib\site-packages\urllib3\util\connection.py", line 85, in create_connection
    raise err
  File "C:\pinokio\api\mirror.git\venv\lib\site-packages\urllib3\util\connection.py", line 73, in create_connection
    sock.connect(sa)
ConnectionRefusedError: [WinError 10061]  Unable to establish connection. Persistent rejection of the target computer

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\pinokio\api\mirror.git\venv\lib\site-packages\urllib3\connectionpool.py", line 789, in urlopen
    response = self._make_request(
  File "C:\pinokio\api\mirror.git\venv\lib\site-packages\urllib3\connectionpool.py", line 495, in _make_request
    conn.request(
  File "C:\pinokio\api\mirror.git\venv\lib\site-packages\urllib3\connection.py", line 398, in request
    self.endheaders()
  File "C:\pinokio\bin\miniconda\lib\http\client.py", line 1278, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "C:\pinokio\bin\miniconda\lib\http\client.py", line 1038, in _send_output
    self.send(msg)
  File "C:\pinokio\bin\miniconda\lib\http\client.py", line 976, in send
    self.connect()
  File "C:\pinokio\api\mirror.git\venv\lib\site-packages\urllib3\connection.py", line 236, in connect
    self.sock = self._new_conn()
  File "C:\pinokio\api\mirror.git\venv\lib\site-packages\urllib3\connection.py", line 211, in _new_conn
    raise NewConnectionError(
urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPConnection object at 0x00000266BDD1CEB0>: Failed to establish a new connection: [WinError 10061]  Unable to establish connection. Persistent rejection of the target computer

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\pinokio\api\mirror.git\venv\lib\site-packages\requests\adapters.py", line 667, in send
    resp = conn.urlopen(
  File "C:\pinokio\api\mirror.git\venv\lib\site-packages\urllib3\connectionpool.py", line 843, in urlopen
    retries = retries.increment(
  File "C:\pinokio\api\mirror.git\venv\lib\site-packages\urllib3\util\retry.py", line 519, in increment
    raise MaxRetryError(_pool, url, reason) from reason  # type: ignore[arg-type]
urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='localhost', port=8080): Max retries exceeded with url: /completion (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x00000266BDD1CEB0>: Failed to establish a new connection: [WinError 10061]  Unable to establish connection. Persistent rejection of the target computer'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\pinokio\api\mirror.git\venv\lib\site-packages\gradio\queueing.py", line 427, in call_prediction
    output = await route_utils.call_process_api(
  File "C:\pinokio\api\mirror.git\venv\lib\site-packages\gradio\route_utils.py", line 232, in call_process_api
    output = await app.get_blocks().process_api(
  File "C:\pinokio\api\mirror.git\venv\lib\site-packages\gradio\blocks.py", line 1484, in process_api
    result = await self.call_function(
  File "C:\pinokio\api\mirror.git\venv\lib\site-packages\gradio\blocks.py", line 1118, in call_function
    prediction = await utils.async_iteration(iterator)
  File "C:\pinokio\api\mirror.git\venv\lib\site-packages\gradio\utils.py", line 514, in async_iteration
    return await iterator.__anext__()
  File "C:\pinokio\api\mirror.git\venv\lib\site-packages\gradio\utils.py", line 507, in __anext__
    return await anyio.to_thread.run_sync(
  File "C:\pinokio\api\mirror.git\venv\lib\site-packages\anyio\to_thread.py", line 56, in run_sync
    return await get_async_backend().run_sync_in_worker_thread(
  File "C:\pinokio\api\mirror.git\venv\lib\site-packages\anyio\_backends\_asyncio.py", line 2177, in run_sync_in_worker_thread
    return await future
  File "C:\pinokio\api\mirror.git\venv\lib\site-packages\anyio\_backends\_asyncio.py", line 859, in run
    result = context.run(func, *args)
  File "C:\pinokio\api\mirror.git\venv\lib\site-packages\gradio\utils.py", line 490, in run_sync_iterator_async
    return next(iterator)
  File "C:\pinokio\api\mirror.git\venv\lib\site-packages\gradio\utils.py", line 653, in gen_wrapper
    yield from f(*args, **kwargs)
  File "C:\pinokio\api\mirror.git\app.py", line 25, in run
    response = requests.post(url, headers=headers, json=data, stream=True)
  File "C:\pinokio\api\mirror.git\venv\lib\site-packages\requests\api.py", line 115, in post
    return request("post", url, data=data, json=json, **kwargs)
  File "C:\pinokio\api\mirror.git\venv\lib\site-packages\requests\api.py", line 59, in request
    return session.request(method=method, url=url, **kwargs)
  File "C:\pinokio\api\mirror.git\venv\lib\site-packages\requests\sessions.py", line 589, in request
    resp = self.send(prep, **send_kwargs)
  File "C:\pinokio\api\mirror.git\venv\lib\site-packages\requests\sessions.py", line 703, in send
    r = adapter.send(request, **kwargs)
  File "C:\pinokio\api\mirror.git\venv\lib\site-packages\requests\adapters.py", line 700, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPConnectionPool(host='localhost', port=8080): Max retries exceeded with url: /completion (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x00000266BDD1CEB0>: Failed to establish a new connection: [WinError 10061]  Unable to establish connection. Persistent rejection of the target computer'))

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\pinokio\api\mirror.git\venv\lib\site-packages\gradio\queueing.py", line 472, in process_events
    response = await self.call_prediction(awake_events, batch)
  File "C:\pinokio\api\mirror.git\venv\lib\site-packages\gradio\queueing.py", line 436, in call_prediction
    raise Exception(str(error) if show_error else None) from error
Exception: None

** The main problem is:
[WinError 10061] Unable to establish connection. Persistent rejection of the target computer**

**Comment by Anubiiiiiiiiiis** [comment]
> > @velikaplan try gradio 4.1.1
> 
> How can I do this?

go to folder: C:\pinokio\api\mirror.git\venv
Active the virtual enviroment with this command (Windows)
.\Scripts\activate

Then uninstall gradio with:
pip uninstall gradio

Then install new gradio version with:
pip install gradio==4.1.1

And close the cmd when finish.

Try again in Pinokio, but now i have another error.. im so close to work
