### ISSUE TITLE
Windows 11 - Image Flicker, No Connection

### ISSUE THREAD

**Issue by purzbeats** [cocktailpeanut/mirror#5]
Pinokio install on Windows 11, RTX 3090

https://github.com/cocktailpeanut/mirror/assets/97489706/3b7abedf-9b27-4295-879c-6e01d3fbb07a

Console keeps throwing these 👇

```
Traceback (most recent call last):
  File "C:\pinokio\bin\miniconda\lib\asyncio\events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
  File "C:\pinokio\bin\miniconda\lib\asyncio\proactor_events.py", line 165, in _call_connection_lost
    self._sock.shutdown(socket.SHUT_RDWR)
ConnectionResetError: [WinError 10054] An existing connection was forcibly closed by the remote host

```

When I hit enter in the prompt box, it doesn't seem to transmit to the language model either.

**Comment by purzbeats** [comment]
I should mention this is latest Pinokio (0.1.50)

**Comment by igor-kurenkov** [comment]
I have same problem on Windows 10, latest Pinokio

**Comment by jajawunderbar** [comment]
Same Problem. Win 11, new Pinokio.

**Comment by Refeistrom** [comment]
it is working for me but with the constant "uploading" flickering using pinokio 0.1.50 on win11

**Comment by jajawunderbar** [comment]
No solution for that, yet? Thanks.

**Comment by SHOSHINXX** [comment]
For me its not possible to Upload a file, do you know how to fix that? 
![mirrpr](https://github.com/cocktailpeanut/mirror/assets/96729010/4a5a0311-7745-44df-ae59-ba3ddadf50e8)

**Comment by SHOSHINXX** [comment]
For me it is not possible to Upload a file, am I to dumb or how do you do that?
